# Site settings
title: Alireza Danaee
description: Alireza Danaee - Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alireza Danaee
user_description: I received the B.Sc. and M.Sc degrees in Electrical Engineering from the University of Kurdistan, Sanandaj, in 2008, and the Shahid Rajaee Teacher Training University, Tehran, in 2013, respectively. I started my Ph.D. at the Pontifical Catholic University of Rio de Janeiro in August 2018, under the supervision of <a href="https://scholar.google.com/citations?user=P0-eVQQAAAAJ&hl=en"target="_blank">Prof. Rodrigo C. de Lamare</a> and <a href="https://scholar.google.com/citations?user=_XSJTowAAAAJ&hl=en"target="_blank">Prof. Vítor H. Nascimento</a>. I am currently working on energy-efficient techniques in Adaptive IoT networks and federated learning.
user_title: PhD Candidate
email: danaee.alireza@gmail.com
github_username:  AlirezaDanaee

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
